### ISSUE TITLE
ERROR: MethodError: no method matching fit

### ISSUE THREAD

**Issue by ruizhuhuang** [BGU-CS-VIL/DPMMSubClusters.jl#7]
julia> ret_values= fit(x,10.0, iters = 100,burnout = 10, gt = y)
ERROR: MethodError: no method matching fit(::Array{Float64,2}, ::Float64; iters=100, burnout=10, gt=[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0  …  6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0])
Closest candidates are:
  fit(::AbstractArray{Float64,2}, ::Float64; iters, init_clusters, seed, verbose, save_model) at /home1/03076/rhuang/.julia/packages/DPMMSubClusters/bM0B6/src/dp-parallel-sampling.jl:83 got unsupported keyword arguments "burnout", "gt"
  fit(::AbstractArray{Float64,2}, ::DPMMSubClusters.distribution_hyper_params, ::Float64; iters, init_clusters, seed, verbose, save_model) at /home1/03076/rhuang/.julia/packages/DPMMSubClusters/bM0B6/src/dp-parallel-sampling.jl:76 got unsupported keyword arguments "burnout", "gt"
Stacktrace:
 [1] kwerr(::NamedTuple{(:iters, :burnout, :gt),Tuple{Int64,Int64,Array{Float64,1}}}, ::Function, ::Array{Float64,2}, ::Float64) at ./error.jl:97
 [2] (::getfield(DPMMSubClusters, Symbol("#kw##fit")))(::NamedTuple{(:iters, :burnout, :gt),Tuple{Int64,Int64,Array{Float64,1}}}, ::typeof(fit), ::Array{Float64,2}, ::Float64) at ./none:0
 [3] top-level scope at none:0

**Comment by dinarior** [comment]
The `burnout` and `gt` are optional keywords which was added in the latest version. You can either remove them (and it will use the default hard-coded values for burnout, and no GT statistics) or the recommended option,  upgrade to the new version.
